spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentmanager?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1024000
      max-request-size: 1024000


mybatis:
  type-aliases-package: com.wjB.studentmanager.domain
  mapper-locations: classpath:mapper/*.xml

